// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: topology.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticModel_GetTopology_FullMethodName      = "/opscopilot.contracts.v1.SemanticModel/GetTopology"
	SemanticModel_GetRecentChanges_FullMethodName = "/opscopilot.contracts.v1.SemanticModel/GetRecentChanges"
)

// SemanticModelClient is the client API for SemanticModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 语义模型服务：拓扑与变更的时点查询（v1.2 C15）
type SemanticModelClient interface {
	// GetTopology 查询时点拓扑。as_of 为空表示当前时刻。
	// RCA 必须传入故障时刻 T0，禁止用当前拓扑分析历史事件。
	GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error)
	// GetRecentChanges 查询节点在窗口内的变更（RCA 证据）。
	GetRecentChanges(ctx context.Context, in *GetRecentChangesRequest, opts ...grpc.CallOption) (*GetRecentChangesResponse, error)
}

type semanticModelClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticModelClient(cc grpc.ClientConnInterface) SemanticModelClient {
	return &semanticModelClient{cc}
}

func (c *semanticModelClient) GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopologyResponse)
	err := c.cc.Invoke(ctx, SemanticModel_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticModelClient) GetRecentChanges(ctx context.Context, in *GetRecentChangesRequest, opts ...grpc.CallOption) (*GetRecentChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentChangesResponse)
	err := c.cc.Invoke(ctx, SemanticModel_GetRecentChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticModelServer is the server API for SemanticModel service.
// All implementations must embed UnimplementedSemanticModelServer
// for forward compatibility.
//
// 语义模型服务：拓扑与变更的时点查询（v1.2 C15）
type SemanticModelServer interface {
	// GetTopology 查询时点拓扑。as_of 为空表示当前时刻。
	// RCA 必须传入故障时刻 T0，禁止用当前拓扑分析历史事件。
	GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error)
	// GetRecentChanges 查询节点在窗口内的变更（RCA 证据）。
	GetRecentChanges(context.Context, *GetRecentChangesRequest) (*GetRecentChangesResponse, error)
	mustEmbedUnimplementedSemanticModelServer()
}

// UnimplementedSemanticModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticModelServer struct{}

func (UnimplementedSemanticModelServer) GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedSemanticModelServer) GetRecentChanges(context.Context, *GetRecentChangesRequest) (*GetRecentChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentChanges not implemented")
}
func (UnimplementedSemanticModelServer) mustEmbedUnimplementedSemanticModelServer() {}
func (UnimplementedSemanticModelServer) testEmbeddedByValue()                       {}

// UnsafeSemanticModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticModelServer will
// result in compilation errors.
type UnsafeSemanticModelServer interface {
	mustEmbedUnimplementedSemanticModelServer()
}

func RegisterSemanticModelServer(s grpc.ServiceRegistrar, srv SemanticModelServer) {
	// If the following call panics, it indicates UnimplementedSemanticModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticModel_ServiceDesc, srv)
}

func _SemanticModel_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticModelServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticModel_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticModelServer).GetTopology(ctx, req.(*GetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticModel_GetRecentChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticModelServer).GetRecentChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticModel_GetRecentChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticModelServer).GetRecentChanges(ctx, req.(*GetRecentChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticModel_ServiceDesc is the grpc.ServiceDesc for SemanticModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opscopilot.contracts.v1.SemanticModel",
	HandlerType: (*SemanticModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopology",
			Handler:    _SemanticModel_GetTopology_Handler,
		},
		{
			MethodName: "GetRecentChanges",
			Handler:    _SemanticModel_GetRecentChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topology.proto",
}
