// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: topology.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopologyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NodeKey  string                 `protobuf:"bytes,2,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	Depth    int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	// RFC3339 时间戳；为空=当前时刻
	AsOf          string `protobuf:"bytes,4,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopologyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTopologyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *GetTopologyRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GetTopologyRequest) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

type TopologyNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeKey       string                 `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	ValidFrom     string                 `protobuf:"bytes,3,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       string                 `protobuf:"bytes,4,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	Confidence    string                 `protobuf:"bytes,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyNode) Reset() {
	*x = TopologyNode{}
	mi := &file_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyNode) ProtoMessage() {}

func (x *TopologyNode) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyNode.ProtoReflect.Descriptor instead.
func (*TopologyNode) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{1}
}

func (x *TopologyNode) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *TopologyNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *TopologyNode) GetValidFrom() string {
	if x != nil {
		return x.ValidFrom
	}
	return ""
}

func (x *TopologyNode) GetValidTo() string {
	if x != nil {
		return x.ValidTo
	}
	return ""
}

func (x *TopologyNode) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *TopologyNode) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type TopologyEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcKey        string                 `protobuf:"bytes,1,opt,name=src_key,json=srcKey,proto3" json:"src_key,omitempty"`
	DstKey        string                 `protobuf:"bytes,2,opt,name=dst_key,json=dstKey,proto3" json:"dst_key,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Confidence    string                 `protobuf:"bytes,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyEdge) Reset() {
	*x = TopologyEdge{}
	mi := &file_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyEdge) ProtoMessage() {}

func (x *TopologyEdge) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyEdge.ProtoReflect.Descriptor instead.
func (*TopologyEdge) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{2}
}

func (x *TopologyEdge) GetSrcKey() string {
	if x != nil {
		return x.SrcKey
	}
	return ""
}

func (x *TopologyEdge) GetDstKey() string {
	if x != nil {
		return x.DstKey
	}
	return ""
}

func (x *TopologyEdge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *TopologyEdge) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *TopologyEdge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TopologyNode        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*TopologyEdge        `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	ResolvedAsOf  string                 `protobuf:"bytes,3,opt,name=resolved_as_of,json=resolvedAsOf,proto3" json:"resolved_as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	mi := &file_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopologyResponse) GetNodes() []*TopologyNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetTopologyResponse) GetEdges() []*TopologyEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *GetTopologyResponse) GetResolvedAsOf() string {
	if x != nil {
		return x.ResolvedAsOf
	}
	return ""
}

type GetRecentChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NodeKey       string                 `protobuf:"bytes,2,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	WindowStart   string                 `protobuf:"bytes,3,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd     string                 `protobuf:"bytes,4,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentChangesRequest) Reset() {
	*x = GetRecentChangesRequest{}
	mi := &file_topology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentChangesRequest) ProtoMessage() {}

func (x *GetRecentChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentChangesRequest.ProtoReflect.Descriptor instead.
func (*GetRecentChangesRequest) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecentChangesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetRecentChangesRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *GetRecentChangesRequest) GetWindowStart() string {
	if x != nil {
		return x.WindowStart
	}
	return ""
}

func (x *GetRecentChangesRequest) GetWindowEnd() string {
	if x != nil {
		return x.WindowEnd
	}
	return ""
}

type ChangeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeKey       string                 `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ChangeType    string                 `protobuf:"bytes,2,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRecord) Reset() {
	*x = ChangeRecord{}
	mi := &file_topology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRecord) ProtoMessage() {}

func (x *ChangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRecord.ProtoReflect.Descriptor instead.
func (*ChangeRecord) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeRecord) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ChangeRecord) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ChangeRecord) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *ChangeRecord) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type GetRecentChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*ChangeRecord        `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentChangesResponse) Reset() {
	*x = GetRecentChangesResponse{}
	mi := &file_topology_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentChangesResponse) ProtoMessage() {}

func (x *GetRecentChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentChangesResponse.ProtoReflect.Descriptor instead.
func (*GetRecentChangesResponse) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecentChangesResponse) GetChanges() []*ChangeRecord {
	if x != nil {
		return x.Changes
	}
	return nil
}

var File_topology_proto protoreflect.FileDescriptor

const file_topology_proto_rawDesc = "" +
	"\n" +
	"\x0etopology.proto\x12\x17opscopilot.contracts.v1\"w\n" +
	"\x12GetTopologyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bnode_key\x18\x02 \x01(\tR\anodeKey\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\x12\x13\n" +
	"\x05as_of\x18\x04 \x01(\tR\x04asOf\"\xb8\x01\n" +
	"\fTopologyNode\x12\x19\n" +
	"\bnode_key\x18\x01 \x01(\tR\anodeKey\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x03 \x01(\tR\tvalidFrom\x12\x19\n" +
	"\bvalid_to\x18\x04 \x01(\tR\avalidTo\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\tR\n" +
	"confidence\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\x94\x01\n" +
	"\fTopologyEdge\x12\x17\n" +
	"\asrc_key\x18\x01 \x01(\tR\x06srcKey\x12\x17\n" +
	"\adst_key\x18\x02 \x01(\tR\x06dstKey\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\tR\n" +
	"confidence\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xb5\x01\n" +
	"\x13GetTopologyResponse\x12;\n" +
	"\x05nodes\x18\x01 \x03(\v2%.opscopilot.contracts.v1.TopologyNodeR\x05nodes\x12;\n" +
	"\x05edges\x18\x02 \x03(\v2%.opscopilot.contracts.v1.TopologyEdgeR\x05edges\x12$\n" +
	"\x0eresolved_as_of\x18\x03 \x01(\tR\fresolvedAsOf\"\x93\x01\n" +
	"\x17GetRecentChangesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bnode_key\x18\x02 \x01(\tR\anodeKey\x12!\n" +
	"\fwindow_start\x18\x03 \x01(\tR\vwindowStart\x12\x1d\n" +
	"\n" +
	"window_end\x18\x04 \x01(\tR\twindowEnd\"\x81\x01\n" +
	"\fChangeRecord\x12\x19\n" +
	"\bnode_key\x18\x01 \x01(\tR\anodeKey\x12\x1f\n" +
	"\vchange_type\x18\x02 \x01(\tR\n" +
	"changeType\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\"[\n" +
	"\x18GetRecentChangesResponse\x12?\n" +
	"\achanges\x18\x01 \x03(\v2%.opscopilot.contracts.v1.ChangeRecordR\achanges2\xf2\x01\n" +
	"\rSemanticModel\x12h\n" +
	"\vGetTopology\x12+.opscopilot.contracts.v1.GetTopologyRequest\x1a,.opscopilot.contracts.v1.GetTopologyResponse\x12w\n" +
	"\x10GetRecentChanges\x120.opscopilot.contracts.v1.GetRecentChangesRequest\x1a1.opscopilot.contracts.v1.GetRecentChangesResponseB%Z#opscopilot/internal/contracts/pb;pbb\x06proto3"

var (
	file_topology_proto_rawDescOnce sync.Once
	file_topology_proto_rawDescData []byte
)

func file_topology_proto_rawDescGZIP() []byte {
	file_topology_proto_rawDescOnce.Do(func() {
		file_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topology_proto_rawDesc), len(file_topology_proto_rawDesc)))
	})
	return file_topology_proto_rawDescData
}

var file_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_topology_proto_goTypes = []any{
	(*GetTopologyRequest)(nil),       // 0: opscopilot.contracts.v1.GetTopologyRequest
	(*TopologyNode)(nil),             // 1: opscopilot.contracts.v1.TopologyNode
	(*TopologyEdge)(nil),             // 2: opscopilot.contracts.v1.TopologyEdge
	(*GetTopologyResponse)(nil),      // 3: opscopilot.contracts.v1.GetTopologyResponse
	(*GetRecentChangesRequest)(nil),  // 4: opscopilot.contracts.v1.GetRecentChangesRequest
	(*ChangeRecord)(nil),             // 5: opscopilot.contracts.v1.ChangeRecord
	(*GetRecentChangesResponse)(nil), // 6: opscopilot.contracts.v1.GetRecentChangesResponse
}
var file_topology_proto_depIdxs = []int32{
	1, // 0: opscopilot.contracts.v1.GetTopologyResponse.nodes:type_name -> opscopilot.contracts.v1.TopologyNode
	2, // 1: opscopilot.contracts.v1.GetTopologyResponse.edges:type_name -> opscopilot.contracts.v1.TopologyEdge
	5, // 2: opscopilot.contracts.v1.GetRecentChangesResponse.changes:type_name -> opscopilot.contracts.v1.ChangeRecord
	0, // 3: opscopilot.contracts.v1.SemanticModel.GetTopology:input_type -> opscopilot.contracts.v1.GetTopologyRequest
	4, // 4: opscopilot.contracts.v1.SemanticModel.GetRecentChanges:input_type -> opscopilot.contracts.v1.GetRecentChangesRequest
	3, // 5: opscopilot.contracts.v1.SemanticModel.GetTopology:output_type -> opscopilot.contracts.v1.GetTopologyResponse
	6, // 6: opscopilot.contracts.v1.SemanticModel.GetRecentChanges:output_type -> opscopilot.contracts.v1.GetRecentChangesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_topology_proto_init() }
func file_topology_proto_init() {
	if File_topology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topology_proto_rawDesc), len(file_topology_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topology_proto_goTypes,
		DependencyIndexes: file_topology_proto_depIdxs,
		MessageInfos:      file_topology_proto_msgTypes,
	}.Build()
	File_topology_proto = out.File
	file_topology_proto_goTypes = nil
	file_topology_proto_depIdxs = nil
}
